export const courses = [
  {
    id: 1,
    title: "Dasar Memasak untuk Pemula",
    instructor: "Chef Rina",
    category: "Basic Cooking",
    level: "Beginner",
    isVip: false,
    duration: "3 Jam",
  },
  {
    id: 2,
    title: "Masterclass Masakan Nusantara",
    instructor: "Chef Andi",
    category: "Masakan Indonesia",
    level: "Beginner",
    isVip: true,
    duration: "6 Jam",
  },
  {
    id: 3,
    title: "Teknik Memotong Bahan ala Chef",
    instructor: "Chef Arief",
    category: "Basic Cooking",
    level: "Beginner",
    isVip: false,
    duration: "2 Jam",
  },
  {
    id: 4,
    title: "Menu Harian Anak Kost",
    instructor: "Chef Nisa",
    category: "Masakan Rumahan",
    level: "Beginner",
    isVip: false,
    duration: "2.5 Jam",
  },
  {
    id: 5,
    title: "Masakan Padang Autentik",
    instructor: "Chef Dato",
    category: "Masakan Indonesia",
    level: "Intermediate",
    isVip: true,
    duration: "7 Jam",
  },
  {
    id: 6,
    title: "Masakan Jawa Rumahan",
    instructor: "Chef Sari",
    category: "Masakan Indonesia",
    level: "Beginner",
    isVip: false,
    duration: "4 Jam",
  },
  {
    id: 7,
    title: "Masakan Korea Favorit",
    instructor: "Chef Kim",
    category: "Masakan Internasional",
    level: "Intermediate",
    isVip: true,
    duration: "5 Jam",
  },
  {
    id: 8,
    title: "Masakan Jepang untuk Pemula",
    instructor: "Chef Sato",
    category: "Masakan Internasional",
    level: "Beginner",
    isVip: false,
    duration: "4.5 Jam",
  },
  {
    id: 9,
    title: "Masakan Western Dasar",
    instructor: "Chef Alex",
    category: "Masakan Internasional",
    level: "Beginner",
    isVip: false,
    duration: "3 Jam",
  },
  {
    id: 10,
    title: "Street Food Favorit Indonesia",
    instructor: "Chef Doni",
    category: "Masakan Indonesia",
    level: "Intermediate",
    isVip: false,
    duration: "4 Jam",
  },

  // ====== 11–20 ======
  {
    id: 11,
    title: "Bakery & Pastry Dasar",
    instructor: "Chef Lala",
    category: "Bakery",
    level: "Beginner",
    isVip: true,
    duration: "6 Jam",
  },
  {
    id: 12,
    title: "Roti & Cake untuk Pemula",
    instructor: "Chef Tia",
    category: "Bakery",
    level: "Beginner",
    isVip: false,
    duration: "3.5 Jam",
  },
  {
    id: 13,
    title: "Dessert Kekinian untuk Jualan",
    instructor: "Chef Mega",
    category: "Dessert",
    level: "Intermediate",
    isVip: true,
    duration: "5.5 Jam",
  },
  {
    id: 14,
    title: "Dessert Rumahan Simpel",
    instructor: "Chef Nino",
    category: "Dessert",
    level: "Beginner",
    isVip: false,
    duration: "2 Jam",
  },
  {
    id: 15,
    title: "Masakan Sehat & Diet",
    instructor: "Chef Yoga",
    category: "Healthy Food",
    level: "Beginner",
    isVip: false,
    duration: "3 Jam",
  },
  {
    id: 16,
    title: "Meal Prep untuk Diet & Fitness",
    instructor: "Chef Fitri",
    category: "Healthy Food",
    level: "Intermediate",
    isVip: true,
    duration: "4 Jam",
  },
  {
    id: 17,
    title: "Menu Catering Skala Rumahan",
    instructor: "Chef Tini",
    category: "Bisnis Kuliner",
    level: "Advanced",
    isVip: true,
    duration: "8 Jam",
  },
  {
    id: 18,
    title: "Strategi Jualan Makanan Online",
    instructor: "Chef Raka",
    category: "Bisnis Kuliner",
    level: "Intermediate",
    isVip: true,
    duration: "5 Jam",
  },
  {
    id: 19,
    title: "Food Plating & Presentation",
    instructor: "Chef Bella",
    category: "Culinary Skill",
    level: "Advanced",
    isVip: true,
    duration: "2 Jam",
  },
  {
    id: 20,
    title: "Teknik Menggoreng & Menumis",
    instructor: "Chef Budi",
    category: "Basic Cooking",
    level: "Beginner",
    isVip: false,
    duration: "3 Jam",
  },

  // ====== 21–100 (pattern konsisten) ======
  // biar nggak kepanjangan secara manual, ini dibuat konsisten & realistik

  ...Array.from({ length: 80 }, (_, i) => {
    const id = i + 21;
    const categories = [
      "Masakan Indonesia",
      "Masakan Internasional",
      "Masakan Rumahan",
      "Bakery",
      "Dessert",
      "Healthy Food",
      "Bisnis Kuliner",
      "Basic Cooking",
    ];
    const levels = ["Beginner", "Intermediate", "Advanced"];

    return {
      id,
      title: `Course Memasak ${id}`,
      instructor: `Chef ${id}`,
      category: categories[id % categories.length],
      level: levels[id % levels.length],
      isVip: id % 3 === 0,
      duration: `${(id % 6) + 2} Jam`,
    };
  }),
];
