const mitra = [
  {
    id: 1,
    nama: "ADING BUDI PRABOWO",
    business_category: "DCCC",
    lat: 1.0466,
    lng: 121.3687,
    kota: "Kabupaten Buol",
    provinsi: "Sulawesi Tengah",
  },
  {
    id: 2,
    nama: "KADEK AYU SUCIARI",
    business_category: "DCCC",
    lat: -8.112,
    lng: 115.0882,
    kota: "Kabupaten Buleleng",
    provinsi: "Bali",
  },
  {
    id: 3,
    nama: "ALGIE ISMI PRAMARTI",
    business_category: "DCCC",
    lat: -6.9147,
    lng: 107.6098,
    kota: "Kota Bandung",
    provinsi: "Jawa Barat",
  },
  {
    id: 4,
    nama: "DENI SUMARNA",
    business_category: "DCCC",
    lat: -6.485,
    lng: 106.8,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 5,
    nama: "ACHMAD TOPAN",
    business_category: "PCCR",
    lat: -6.595,
    lng: 106.8167,
    kota: "Kota Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 6,
    nama: "MEGA ARUM SETIARINI",
    business_category: "DCCC",
    lat: -2.2096,
    lng: 113.9213,
    kota: "Kota Palangka Raya",
    provinsi: "Kalimantan Tengah",
  },
  {
    id: 7,
    nama: "SUHARIYANTO",
    business_category: "PFFR",
    lat: -2.6846,
    lng: 111.6241,
    kota: "Kabupaten Kotawaringin Barat",
    provinsi: "Kalimantan Tengah",
  },
  {
    id: 8,
    nama: "NUR ELAH",
    business_category: "DCSA",
    lat: -6.9222,
    lng: 106.9296,
    kota: "Kota Sukabumi",
    provinsi: "Jawa Barat",
  },
  {
    id: 9,
    nama: "IKA",
    business_category: "DPKB",
    lat: -7.485,
    lng: 108.792,
    kota: "Kabupaten Cilacap",
    provinsi: "Jawa Tengah",
  },
  {
    id: 10,
    nama: "YULI YULIAWATI",
    business_category: "DCCC",
    lat: -7.2167,
    lng: 107.9,
    kota: "Kabupaten Garut",
    provinsi: "Jawa Barat",
  },

  {
    id: 11,
    nama: "DIKI ARIYANDI SAPUTRA",
    business_category: "DCCC",
    lat: -6.8595,
    lng: 106.9207,
    kota: "Kabupaten Sukabumi",
    provinsi: "Jawa Barat",
  },
  {
    id: 12,
    nama: "MEILANNI",
    business_category: "DCCC",
    lat: -8.639,
    lng: 115.2,
    kota: "Kota Denpasar",
    provinsi: "Bali",
  },
  {
    id: 13,
    nama: "YULIANA",
    business_category: "PCCR",
    lat: 0.1324,
    lng: 117.4854,
    kota: "Kota Bontang",
    provinsi: "Kalimantan Timur",
  },
  {
    id: 14,
    nama: "GITA KUSUMA",
    business_category: "DCCC",
    lat: -7.545,
    lng: 112.233,
    kota: "Kabupaten Jombang",
    provinsi: "Jawa Timur",
  },
  {
    id: 15,
    nama: "APRITASARI",
    business_category: "DCSA",
    lat: -6.11,
    lng: 106.15,
    kota: "Kabupaten Serang",
    provinsi: "Banten",
  },
  {
    id: 16,
    nama: "DINA ROSDIANA",
    business_category: "DCSA",
    lat: -6.189,
    lng: 106.625,
    kota: "Kota Tangerang",
    provinsi: "Banten",
  },
  {
    id: 17,
    nama: "RIRIN RATNASARI",
    business_category: "DCSA",
    lat: -5.3817,
    lng: 105.2531,
    kota: "Kabupaten Lampung Selatan",
    provinsi: "Lampung",
  },
  {
    id: 18,
    nama: "ALIS FARICHANA",
    business_category: "DCSA",
    lat: -7.4465,
    lng: 112.7173,
    kota: "Kabupaten Sidoarjo",
    provinsi: "Jawa Timur",
  },
  {
    id: 19,
    nama: "SONIA EKA PUTRI",
    business_category: "DCCC",
    lat: -7.316,
    lng: 110.175,
    kota: "Kabupaten Temanggung",
    provinsi: "Jawa Tengah",
  },
  {
    id: 20,
    nama: "MELLY",
    business_category: "DCCC",
    lat: -0.0617,
    lng: 100.6556,
    kota: "Kabupaten Lima Puluh Kota",
    provinsi: "Sumatera Barat",
  },

  {
    id: 21,
    nama: "MEIKA",
    business_category: "DCCC",
    lat: -6.6944,
    lng: 110.8367,
    kota: "Kabupaten Jepara",
    provinsi: "Jawa Tengah",
  },
  {
    id: 22,
    nama: "ERNITA",
    business_category: "DCCC",
    lat: -6.9333,
    lng: 107.47,
    kota: "Kabupaten Bandung Barat",
    provinsi: "Jawa Barat",
  },
  {
    id: 23,
    nama: "FERLI ANDINA",
    business_category: "PCCR",
    lat: -6.2,
    lng: 106.7833,
    kota: "Kota Jakarta Barat",
    provinsi: "DKI Jakarta",
  },
  {
    id: 24,
    nama: "PARTIKA DEWI",
    business_category: "DCSA",
    lat: 0.5071,
    lng: 101.4478,
    kota: "Kota Pekanbaru",
    provinsi: "Riau",
  },
  {
    id: 25,
    nama: "AJM EXSPRESS/BINTANG CARGO",
    business_category: "DCCC",
    lat: -3.3683,
    lng: 135.5011,
    kota: "Kabupaten Nabire",
    provinsi: "Papua Tengah",
  },
  {
    id: 26,
    nama: "ADITYA MAHENDRA",
    business_category: "CCRO",
    lat: 1.6666,
    lng: 101.4478,
    kota: "Kabupaten Bengkalis",
    provinsi: "Riau",
  },
  {
    id: 27,
    nama: "NURI RINJANI",
    business_category: "DCCC",
    lat: -6.8581,
    lng: 107.9236,
    kota: "Kabupaten Sumedang",
    provinsi: "Jawa Barat",
  },
  {
    id: 28,
    nama: "RIA RISKI TETEI UTAMI",
    business_category: "DPKB",
    lat: -2.115,
    lng: 115.02,
    kota: "Kabupaten Kotawaringin Timur",
    provinsi: "Kalimantan Tengah",
  },
  {
    id: 29,
    nama: "FITRIANI",
    business_category: "CCRO",
    lat: -6.804,
    lng: 110.84,
    kota: "Kabupaten Demak",
    provinsi: "Jawa Tengah",
  },
  {
    id: 30,
    nama: "EMA MARDIANI",
    business_category: "DCCC",
    lat: -6.4025,
    lng: 107.4333,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },

  {
    id: 31,
    nama: "I GUSTI AGUNG AYU ALIT CANDRA DEWI",
    business_category: "PFFR",
    lat: -8.45,
    lng: 115.6167,
    kota: "Kabupaten Karangasem",
    provinsi: "Bali",
  },
  {
    id: 32,
    nama: "DIAN SITI KHUMAEROH",
    business_category: "DCSA",
    lat: -6.8721,
    lng: 109.0423,
    kota: "Kabupaten Tegal",
    provinsi: "Jawa Tengah",
  },
  {
    id: 33,
    nama: "MIRA",
    business_category: "DCSA",
    lat: -6.485,
    lng: 106.895,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 34,
    nama: "LINDA",
    business_category: "DCSA",
    lat: -7.418,
    lng: 109.255,
    kota: "Kabupaten Banyumas",
    provinsi: "Jawa Tengah",
  },
  {
    id: 35,
    nama: "FITRI AJANA",
    business_category: "DCSA",
    lat: -6.485,
    lng: 106.8,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 36,
    nama: "RISKA RAHAYU",
    business_category: "CCRO",
    lat: -6.25,
    lng: 106.5,
    kota: "Kabupaten Tangerang",
    provinsi: "Banten",
  },
  {
    id: 37,
    nama: "MUHAMMAD NUR SYAFI'I PRATAMA",
    business_category: "DCCC",
    lat: -6.33,
    lng: 106.9,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 38,
    nama: "SITI RAHMAWATI",
    business_category: "PCCR",
    lat: -7.705,
    lng: 110.606,
    kota: "Kabupaten Sleman",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 39,
    nama: "ELSA YUMAVELISIA",
    business_category: "PCCR",
    lat: -8.095,
    lng: 112.165,
    kota: "Kabupaten Malang",
    provinsi: "Jawa Timur",
  },
  {
    id: 40,
    nama: "NUR AISYAH (AISH)",
    business_category: "DCCC",
    lat: -6.2833,
    lng: 107.1,
    kota: "Kabupaten Karawang",
    provinsi: "Jawa Barat",
  },

  {
    id: 41,
    nama: "SRI WAHYUNI",
    business_category: "DCSA",
    lat: 0.5104,
    lng: 101.4478,
    kota: "Kota Pekanbaru",
    provinsi: "Riau",
  },
  {
    id: 42,
    nama: "WULAN PANGGABEAN",
    business_category: "PCCR",
    lat: 2.017,
    lng: 99.0667,
    kota: "Kabupaten Tapanuli Utara",
    provinsi: "Sumatera Utara",
  },
  {
    id: 43,
    nama: "AMELIA",
    business_category: "PCCR",
    lat: 1.4748,
    lng: 124.8421,
    kota: "Kota Manado",
    provinsi: "Sulawesi Utara",
  },
  {
    id: 44,
    nama: "AKHMAD NUR KHOLIS",
    business_category: "DCCC",
    lat: -6.8721,
    lng: 109.0423,
    kota: "Kabupaten Tegal",
    provinsi: "Jawa Tengah",
  },
  {
    id: 45,
    nama: "SUMIATI DEVI ARDIANTI (DEVI)",
    business_category: "CCRO",
    lat: -6.395,
    lng: 106.98,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 46,
    nama: "SUSILAWATI",
    business_category: "DCCC",
    lat: -8.65,
    lng: 116.53,
    kota: "Kabupaten Lombok Timur",
    provinsi: "Nusa Tenggara Barat",
  },
  {
    id: 47,
    nama: "SITI HALIMATUS",
    business_category: "DCSA",
    lat: -7.705,
    lng: 114.0,
    kota: "Kabupaten Probolinggo",
    provinsi: "Jawa Timur",
  },
  {
    id: 48,
    nama: "VINISA SOFI",
    business_category: "DCCC",
    lat: -7.005,
    lng: 110.4381,
    kota: "Kota Semarang",
    provinsi: "Jawa Tengah",
  },
  {
    id: 49,
    nama: "WANDA ADI SAPUTRA",
    business_category: "DCSA",
    lat: -5.05,
    lng: 105.2,
    kota: "Kota Bandar Lampung",
    provinsi: "Lampung",
  },
  {
    id: 50,
    nama: "IGNES KHARISMA",
    business_category: "DCCC",
    lat: -8.095,
    lng: 112.165,
    kota: "Kabupaten Malang",
    provinsi: "Jawa Timur",
  },

  {
    id: 51,
    nama: "HAESUSI",
    business_category: "DCCC",
    lat: -6.13,
    lng: 106.88,
    kota: "Kota Jakarta Timur",
    provinsi: "DKI Jakarta",
  },
  {
    id: 52,
    nama: "BAGUS MOCH SAHID",
    business_category: "DPKB",
    lat: 0.1324,
    lng: 117.4854,
    kota: "Kota Bontang",
    provinsi: "Kalimantan Timur",
  },
  {
    id: 53,
    nama: "CITRA YOLLANDA",
    business_category: "DCCC",
    lat: 0.3667,
    lng: 101.2,
    kota: "Kabupaten Kampar",
    provinsi: "Riau",
  },
  {
    id: 54,
    nama: "DINA IRNI YUSNITA",
    business_category: "CCRO",
    lat: -7.9666,
    lng: 112.6326,
    kota: "Kota Malang",
    provinsi: "Jawa Timur",
  },
  {
    id: 55,
    nama: "GEK GALUH",
    business_category: "DCCC",
    lat: -8.65,
    lng: 115.2167,
    kota: "Kota Denpasar",
    provinsi: "Bali",
  },
  {
    id: 56,
    nama: "SR REIYNE NUR YOULLA IESMELLIA",
    business_category: "DCCC",
    lat: -6.9147,
    lng: 107.6098,
    kota: "Kota Bandung",
    provinsi: "Jawa Barat",
  },
  {
    id: 57,
    nama: "RINI LESTARI",
    business_category: "MHRE",
    lat: -2.9909,
    lng: 104.7566,
    kota: "Kota Palembang",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 58,
    nama: "EGA",
    business_category: "CCRO",
    lat: -7.07,
    lng: 110.35,
    kota: "Kabupaten Semarang",
    provinsi: "Jawa Tengah",
  },
  {
    id: 59,
    nama: "ANANDA ANING PRADITA",
    business_category: "DPKB",
    lat: -7.767,
    lng: 110.293,
    kota: "Kabupaten Bantul",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 60,
    nama: "VICKY NOVRIAN",
    business_category: "CCRO",
    lat: -7.9666,
    lng: 112.6326,
    kota: "Kota Malang",
    provinsi: "Jawa Timur",
  },

  {
    id: 61,
    nama: "DEVITA CHANIA",
    business_category: "DCCC",
    lat: -2.9909,
    lng: 104.7566,
    kota: "Kota Palembang",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 62,
    nama: "BU MMS ATW MMH NN",
    business_category: "DCSA",
    lat: -6.348,
    lng: 106.58,
    kota: "Kota Tangerang Selatan",
    provinsi: "Banten",
  },
  {
    id: 63,
    nama: "INDRA WINARNO",
    business_category: "DCCC",
    lat: -6.13,
    lng: 106.88,
    kota: "Kota Jakarta Timur",
    provinsi: "DKI Jakarta",
  },
  {
    id: 64,
    nama: "MAMA BIMO/IBU LILIS",
    business_category: "DCCC",
    lat: -6.485,
    lng: 106.895,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 65,
    nama: "ELIS SUSILAWATI",
    business_category: "DCCC",
    lat: -6.7,
    lng: 106.8,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 66,
    nama: "KADEK AYU KARIASIH",
    business_category: "DCCC",
    lat: -8.112,
    lng: 115.0882,
    kota: "Kabupaten Buleleng",
    provinsi: "Bali",
  },
  {
    id: 67,
    nama: "MARGARETA FLORIDA",
    business_category: "PCCR",
    lat: -2.5916,
    lng: 140.669,
    kota: "Kota Jayapura",
    provinsi: "Papua",
  },
  {
    id: 68,
    nama: "NUR SUBKHAN (IZZA)",
    business_category: "PFFR",
    lat: -7.314,
    lng: 110.176,
    kota: "Kabupaten Temanggung",
    provinsi: "Jawa Tengah",
  },
  {
    id: 69,
    nama: "DEASY ASTUTI",
    business_category: "DCSA",
    lat: -6.2146,
    lng: 106.8721,
    kota: "Kota Jakarta Selatan",
    provinsi: "DKI Jakarta",
  },
  {
    id: 70,
    nama: "TUTI",
    business_category: "DCSA",
    lat: -6.705,
    lng: 106.7,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },

  {
    id: 71,
    nama: "FITRIANI USMAN",
    business_category: "PFFR",
    lat: 1.06,
    lng: 127.84,
    kota: "Kota Ternate",
    provinsi: "Maluku Utara",
  },
  {
    id: 72,
    nama: "YASMINTHA STEVANUS",
    business_category: "DCCC",
    lat: -7.139,
    lng: 110.405,
    kota: "Kota Salatiga",
    provinsi: "Jawa Tengah",
  },
  {
    id: 73,
    nama: "ELIS TIANA",
    business_category: "DCCC",
    lat: 0.88,
    lng: 100.3,
    kota: "Kabupaten Rokan Hulu",
    provinsi: "Riau",
  },
  {
    id: 74,
    nama: "NOVIE DEM AREAYANTO",
    business_category: "PFFR",
    lat: -7.6317,
    lng: 111.5239,
    kota: "Kabupaten Madiun",
    provinsi: "Jawa Timur",
  },
  {
    id: 75,
    nama: "TANTI HARYANTI",
    business_category: "PFFR",
    lat: -6.28,
    lng: 106.74,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 76,
    nama: "YULI WIDYAYANTI",
    business_category: "DCCC",
    lat: -8.55,
    lng: 115.18,
    kota: "Kabupaten Badung",
    provinsi: "Bali",
  },
  {
    id: 77,
    nama: "EEN ANDRIYENI",
    business_category: "PFFR",
    lat: -2.8833,
    lng: 104.75,
    kota: "Kota Palembang",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 78,
    nama: "FATHAN ANSYURULLAH",
    business_category: "DCCC",
    lat: -7.67,
    lng: 109.65,
    kota: "Kabupaten Kebumen",
    provinsi: "Jawa Tengah",
  },
  {
    id: 79,
    nama: "DESI TRIYANA",
    business_category: "DCCC",
    lat: -3.4344,
    lng: 104.235,
    kota: "Kabupaten Ogan Ilir",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 80,
    nama: "JULIANI KHAIRUNNISA",
    business_category: "DCCC",
    lat: -6.15,
    lng: 107.02,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },

  {
    id: 81,
    nama: "JAYA PERKASA",
    business_category: "PCCR",
    lat: -6.47,
    lng: 107.35,
    kota: "Kabupaten Karawang",
    provinsi: "Jawa Barat",
  },
  {
    id: 82,
    nama: "MUHAMAD SOBRI",
    business_category: "DCCC",
    lat: -6.25,
    lng: 106.15,
    kota: "Kabupaten Tangerang",
    provinsi: "Banten",
  },
  {
    id: 83,
    nama: "M. RECHAN. T. S",
    business_category: "PCCR",
    lat: -6.6,
    lng: 106.8,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 84,
    nama: "FITRIANA",
    business_category: "DCCC",
    lat: -2.315,
    lng: 115.495,
    kota: "Kabupaten Tanah Bumbu",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 85,
    nama: "BU YATI",
    business_category: "DCCC",
    lat: -6.15,
    lng: 106.73,
    kota: "Kota Jakarta Barat",
    provinsi: "DKI Jakarta",
  },
  {
    id: 86,
    nama: "ROHADI WIJAYA",
    business_category: "PFFR",
    lat: -6.375,
    lng: 108.3,
    kota: "Kabupaten Indramayu",
    provinsi: "Jawa Barat",
  },
  {
    id: 87,
    nama: "FAUZIAH",
    business_category: "PFFR",
    lat: 1.5,
    lng: 102.1,
    kota: "Kabupaten Bengkalis",
    provinsi: "Riau",
  },
  {
    id: 88,
    nama: "MUH. ERWIN",
    business_category: "DCCC",
    lat: -5.005,
    lng: 119.573,
    kota: "Kota Makassar",
    provinsi: "Sulawesi Selatan",
  },
  {
    id: 89,
    nama: "HOERON ANISA",
    business_category: "DCCC",
    lat: -6.893,
    lng: 107.573,
    kota: "Kota Cimahi",
    provinsi: "Jawa Barat",
  },
  {
    id: 90,
    nama: "TRIANA SERI",
    business_category: "DCSA",
    lat: -6.15,
    lng: 106.5,
    kota: "Kabupaten Tangerang",
    provinsi: "Banten",
  },

  {
    id: 91,
    nama: "YUKI ISNANDANI",
    business_category: "DCCC",
    lat: -7.395,
    lng: 109.4,
    kota: "Kabupaten Banyumas",
    provinsi: "Jawa Tengah",
  },
  {
    id: 92,
    nama: "RIMA",
    business_category: "DCCC",
    lat: -7.3,
    lng: 106.85,
    kota: "Kabupaten Sukabumi",
    provinsi: "Jawa Barat",
  },
  {
    id: 93,
    nama: "MUHTADI",
    business_category: "DCCC",
    lat: -6.22,
    lng: 106.83,
    kota: "Kota Jakarta Selatan",
    provinsi: "DKI Jakarta",
  },
  {
    id: 94,
    nama: "KOMANG ENY PRIMAYANI",
    business_category: "DCCC",
    lat: -8.65,
    lng: 115.18,
    kota: "Kabupaten Badung",
    provinsi: "Bali",
  },
  {
    id: 95,
    nama: "NUR SILVI ZAHRA",
    business_category: "DCCC",
    lat: -3.3,
    lng: 116.2,
    kota: "Kabupaten Kotabaru",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 96,
    nama: "MARSANI",
    business_category: "PCCR",
    lat: -6.15,
    lng: 106.2,
    kota: "Kabupaten Serang",
    provinsi: "Banten",
  },
  {
    id: 97,
    nama: "ARIS DESIYANTI",
    business_category: "DCSA",
    lat: -6.9,
    lng: 112.05,
    kota: "Kabupaten Tuban",
    provinsi: "Jawa Timur",
  },
  {
    id: 98,
    nama: "BUNGA",
    business_category: "DCSA",
    lat: -7.095,
    lng: 110.912,
    kota: "Kabupaten Boyolali",
    provinsi: "Jawa Tengah",
  },
  {
    id: 99,
    nama: "ANDI ERWIN MARTISANDI",
    business_category: "PCCR",
    lat: 3.3,
    lng: 117.6,
    kota: "Kabupaten Nunukan",
    provinsi: "Kalimantan Utara",
  },
  {
    id: 100,
    nama: "NAZARULLAH",
    business_category: "DCCC",
    lat: -0.5021,
    lng: 117.1536,
    kota: "Kota Samarinda",
    provinsi: "Kalimantan Timur",
  },
  {
    id: 101,
    nama: "NOVITA LISNAWATI",
    business_category: "DPKB",
    lat: 1.0466,
    lng: 104.0041,
    kota: "Kota Tanjung Pinang",
    provinsi: "Kepulauan Riau",
  },
  {
    id: 102,
    nama: "SITI YULIYANTI (YANTI)",
    business_category: "DCCC",
    lat: -6.2383,
    lng: 106.6356,
    kota: "Kota Tangerang",
    provinsi: "Banten",
  },
  {
    id: 103,
    nama: "ANGGIT TRIANI HERMAWATI",
    business_category: "DCCR",
    lat: -7.4214,
    lng: 109.2345,
    kota: "Kabupaten Banyumas",
    provinsi: "Jawa Tengah",
  },
  {
    id: 104,
    nama: "RENITA",
    business_category: "PFFR",
    lat: -2.9911,
    lng: 104.7567,
    kota: "Kota Palembang",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 105,
    nama: "MELISA",
    business_category: "DCSA",
    lat: -6.8696,
    lng: 109.1372,
    kota: "Kabupaten Brebes",
    provinsi: "Jawa Tengah",
  },
  {
    id: 106,
    nama: "KIKI",
    business_category: "PCCR",
    lat: -8.6492,
    lng: 116.3249,
    kota: "Kabupaten Lombok Tengah",
    provinsi: "Nusa Tenggara Barat",
  },
  {
    id: 107,
    nama: "ENDANG",
    business_category: "DCCC",
    lat: -6.9836,
    lng: 110.2038,
    kota: "Kota Semarang",
    provinsi: "Jawa Tengah",
  },
  {
    id: 108,
    nama: "BAIDARI",
    business_category: "DCCC",
    lat: -7.1167,
    lng: 113.4713,
    kota: "Kabupaten Pamekasan",
    provinsi: "Jawa Timur",
  },
  {
    id: 109,
    nama: "MELISA",
    business_category: "PCCR",
    lat: -0.0225,
    lng: 109.3303,
    kota: "Kota Pontianak",
    provinsi: "Kalimantan Barat",
  },
  {
    id: 110,
    nama: "LASWATI PANUNTUN WIDOTAMI",
    business_category: "PCCR",
    lat: -7.9797,
    lng: 114.2496,
    kota: "Kabupaten Banyuwangi",
    provinsi: "Jawa Timur",
  },

  {
    id: 111,
    nama: "ENDANG WIDYARTI",
    business_category: "DCCC",
    lat: -8.1713,
    lng: 113.7021,
    kota: "Kabupaten Jember",
    provinsi: "Jawa Timur",
  },
  {
    id: 112,
    nama: "NERA DEWI OKTAVINA",
    business_category: "DCSA",
    lat: -6.6024,
    lng: 111.0368,
    kota: "Kabupaten Pati",
    provinsi: "Jawa Tengah",
  },
  {
    id: 113,
    nama: "INDRI IRA LISTIANTI",
    business_category: "DCSA",
    lat: -7.3896,
    lng: 109.3634,
    kota: "Kabupaten Banyumas",
    provinsi: "Jawa Tengah",
  },
  {
    id: 114,
    nama: "ANA MARDIANA",
    business_category: "PCCR",
    lat: -2.9911,
    lng: 104.7567,
    kota: "Kota Palembang",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 115,
    nama: "ELLY",
    business_category: "DCCC",
    lat: -7.0301,
    lng: 113.2514,
    kota: "Kabupaten Sampang",
    provinsi: "Jawa Timur",
  },
  {
    id: 116,
    nama: "JOANNA",
    business_category: "DCCC",
    lat: -8.6856,
    lng: 115.2211,
    kota: "Kota Denpasar",
    provinsi: "Bali",
  },
  {
    id: 117,
    nama: "ROIS WILLY",
    business_category: "DCCC",
    lat: -6.6783,
    lng: 111.0437,
    kota: "Kabupaten Pati",
    provinsi: "Jawa Tengah",
  },
  {
    id: 118,
    nama: "BELA MISY KHOIRUNISA",
    business_category: "DCSA",
    lat: -6.2644,
    lng: 107.3916,
    kota: "Kabupaten Karawang",
    provinsi: "Jawa Barat",
  },
  {
    id: 119,
    nama: "SOFAH",
    business_category: "DCCC",
    lat: -6.1185,
    lng: 106.6134,
    kota: "Kota Tangerang",
    provinsi: "Banten",
  },
  {
    id: 120,
    nama: "I KADEK ANDI MAHENDRA",
    business_category: "DCSA",
    lat: -8.5442,
    lng: 115.2065,
    kota: "Kota Denpasar",
    provinsi: "Bali",
  },

  {
    id: 121,
    nama: "ZULNEDI",
    business_category: "DCCC",
    lat: -0.9141,
    lng: 100.3601,
    kota: "Kabupaten Agam",
    provinsi: "Sumatera Barat",
  },
  {
    id: 122,
    nama: "VIBRA ATIKA FARIA",
    business_category: "DCCC",
    lat: -7.2609,
    lng: 112.6426,
    kota: "Kabupaten Sidoarjo",
    provinsi: "Jawa Timur",
  },
  {
    id: 123,
    nama: "WIHARTI",
    business_category: "PFFR",
    lat: -6.8711,
    lng: 109.1284,
    kota: "Kabupaten Brebes",
    provinsi: "Jawa Tengah",
  },
  {
    id: 124,
    nama: "LENIA RATNA SUSANTI",
    business_category: "PCCR",
    lat: -7.2279,
    lng: 107.9087,
    kota: "Kabupaten Garut",
    provinsi: "Jawa Barat",
  },
  {
    id: 125,
    nama: "ALFI ROYAN",
    business_category: "DCCC",
    lat: -3.4324,
    lng: 104.2431,
    kota: "Kabupaten Muara Enim",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 126,
    nama: "MAYA ASTRIA",
    business_category: "PFFR",
    lat: -6.0194,
    lng: 107.3346,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 127,
    nama: "DANIS RAHAYU",
    business_category: "DCCC",
    lat: -6.4213,
    lng: 106.7312,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 128,
    nama: "RINA",
    business_category: "PCCR",
    lat: -6.2356,
    lng: 107.0835,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 129,
    nama: "DENI TARSA NARIA",
    business_category: "DCCC",
    lat: -6.8581,
    lng: 107.9106,
    kota: "Kabupaten Bandung",
    provinsi: "Jawa Barat",
  },
  {
    id: 130,
    nama: "NINA NURWANTI",
    business_category: "DCCC",
    lat: -6.3356,
    lng: 106.9037,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },

  {
    id: 131,
    nama: "YULI KURNIATI",
    business_category: "CCRO",
    lat: -6.1067,
    lng: 106.5314,
    kota: "Kabupaten Tangerang",
    provinsi: "Banten",
  },
  {
    id: 132,
    nama: "KEVIN HUTABARAT",
    business_category: "DCCC",
    lat: 2.1003,
    lng: 99.8315,
    kota: "Kabupaten Samosir",
    provinsi: "Sumatera Utara",
  },
  {
    id: 133,
    nama: "SYAFITRI YANA",
    business_category: "DCSA",
    lat: 5.1761,
    lng: 95.9386,
    kota: "Kabupaten Aceh Utara",
    provinsi: "Aceh",
  },
  {
    id: 134,
    nama: "AHMAD ZAINI",
    business_category: "DCCC",
    lat: -2.7485,
    lng: 114.2632,
    kota: "Kabupaten Kapuas",
    provinsi: "Kalimantan Tengah",
  },
  {
    id: 135,
    nama: "WIJOKO HARYADI",
    business_category: "DCSA",
    lat: -6.3272,
    lng: 107.0121,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 136,
    nama: "LADY DIANA MERCELINA",
    business_category: "DCCC",
    lat: -3.4804,
    lng: 115.9468,
    kota: "Kabupaten Tanah Bumbu",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 137,
    nama: "RIA BUDIARTI",
    business_category: "DCCC",
    lat: 0.7362,
    lng: 101.6321,
    kota: "Kabupaten Siak",
    provinsi: "Riau",
  },
  {
    id: 138,
    nama: "BELLA",
    business_category: "PFFR",
    lat: -8.1586,
    lng: 112.6593,
    kota: "Kabupaten Malang",
    provinsi: "Jawa Timur",
  },
  {
    id: 139,
    nama: "ICHA",
    business_category: "CCRO",
    lat: -2.9756,
    lng: 115.1124,
    kota: "Kabupaten Kotabaru",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 140,
    nama: "MAYA MARISA",
    business_category: "DCCC",
    lat: 5.5532,
    lng: 95.3175,
    kota: "Kota Banda Aceh",
    provinsi: "Aceh",
  },

  {
    id: 141,
    nama: "EILFAD IKMAL HADI",
    business_category: "DCSA",
    lat: -7.0446,
    lng: 112.7441,
    kota: "Kabupaten Gresik",
    provinsi: "Jawa Timur",
  },
  {
    id: 142,
    nama: "ANGGELINA PUTRI",
    business_category: "DCCC",
    lat: -6.5438,
    lng: 108.0583,
    kota: "Kabupaten Indramayu",
    provinsi: "Jawa Barat",
  },
  {
    id: 143,
    nama: "DONI",
    business_category: "PFFR",
    lat: -7.1656,
    lng: 112.6114,
    kota: "Kabupaten Sidoarjo",
    provinsi: "Jawa Timur",
  },
  {
    id: 144,
    nama: "ETTY HARDIANA",
    business_category: "DCSA",
    lat: -6.2359,
    lng: 107.0037,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 145,
    nama: "BUNGA MERIS",
    business_category: "DCCC",
    lat: -7.7774,
    lng: 110.3292,
    kota: "Kabupaten Bantul",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 146,
    nama: "SANTI",
    business_category: "DCSA",
    lat: -6.1966,
    lng: 106.7814,
    kota: "Kota Jakarta Barat",
    provinsi: "DKI Jakarta",
  },
  {
    id: 147,
    nama: "SRI WAHYUNI",
    business_category: "DCSA",
    lat: -2.2096,
    lng: 113.9213,
    kota: "Kota Palangka Raya",
    provinsi: "Kalimantan Tengah",
  },
  {
    id: 148,
    nama: "NORA FERNANDEZ",
    business_category: "DCCC",
    lat: -7.5755,
    lng: 110.2568,
    kota: "Kabupaten Sleman",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 149,
    nama: "RAGIL ASYIFA MAYORI",
    business_category: "DCCC",
    lat: 1.0114,
    lng: 103.3946,
    kota: "Kabupaten Bintan",
    provinsi: "Kepulauan Riau",
  },
  {
    id: 150,
    nama: "EKA",
    business_category: "PCCR",
    lat: -10.1718,
    lng: 123.607,
    kota: "Kota Kupang",
    provinsi: "Nusa Tenggara Timur",
  },

  {
    id: 151,
    nama: "BAPAK APENG",
    business_category: "DCCC",
    lat: -7.2307,
    lng: 112.7351,
    kota: "Kota Surabaya",
    provinsi: "Jawa Timur",
  },
  {
    id: 152,
    nama: "AYU NOVITA DEWI",
    business_category: "PFFR",
    lat: -8.7012,
    lng: 115.1986,
    kota: "Kabupaten Badung",
    provinsi: "Bali",
  },
  {
    id: 153,
    nama: "AYU NOVIANTI",
    business_category: "DCCC",
    lat: 1.6677,
    lng: 101.4479,
    kota: "Kabupaten Bengkalis",
    provinsi: "Riau",
  },
  {
    id: 154,
    nama: "YULIAN FANININGSIH",
    business_category: "DCCC",
    lat: -6.9698,
    lng: 110.2594,
    kota: "Kota Semarang",
    provinsi: "Jawa Tengah",
  },
  {
    id: 155,
    nama: "WINDY",
    business_category: "DCCC",
    lat: -6.4776,
    lng: 107.0374,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 156,
    nama: "RIZVI AGUSTIN",
    business_category: "DCCC",
    lat: -7.0286,
    lng: 107.8194,
    kota: "Kabupaten Bandung",
    provinsi: "Jawa Barat",
  },
  {
    id: 157,
    nama: "ANIS",
    business_category: "DCCC",
    lat: -6.3297,
    lng: 108.0895,
    kota: "Kabupaten Indramayu",
    provinsi: "Jawa Barat",
  },
  {
    id: 158,
    nama: "THIERY GERALDINE RUMENGAN",
    business_category: "DCCC",
    lat: -6.2767,
    lng: 106.9745,
    kota: "Kota Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 159,
    nama: "FIQKI AL IKHSAN LUBIS",
    business_category: "CCRO",
    lat: 3.7064,
    lng: 98.6821,
    kota: "Kota Medan",
    provinsi: "Sumatera Utara",
  },
  {
    id: 160,
    nama: "MAMIK",
    business_category: "CCRO",
    lat: 0.1324,
    lng: 117.4697,
    kota: "Kota Bontang",
    provinsi: "Kalimantan Timur",
  },

  {
    id: 161,
    nama: "DEWI NOVITA DZULMAR",
    business_category: "DCCC",
    lat: -2.1578,
    lng: 115.3826,
    kota: "Kabupaten Kotabaru",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 162,
    nama: "MAYA WIJA SARI",
    business_category: "DCCC",
    lat: -2.3076,
    lng: 102.7135,
    kota: "Kabupaten Bungo",
    provinsi: "Jambi",
  },
  {
    id: 163,
    nama: "RENI EKA SAPUTRI",
    business_category: "DCCC",
    lat: -6.5649,
    lng: 107.7612,
    kota: "Kabupaten Subang",
    provinsi: "Jawa Barat",
  },
  {
    id: 164,
    nama: "SUTIKNO",
    business_category: "DCCC",
    lat: -6.8891,
    lng: 112.0456,
    kota: "Kabupaten Lamongan",
    provinsi: "Jawa Timur",
  },
  {
    id: 165,
    nama: "NORSIFAH",
    business_category: "DCCC",
    lat: -3.4627,
    lng: 114.7744,
    kota: "Kabupaten Banjar",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 166,
    nama: "AYU MERLIANA",
    business_category: "CCRO",
    lat: -8.5412,
    lng: 115.2169,
    kota: "Kota Denpasar",
    provinsi: "Bali",
  },
  {
    id: 167,
    nama: "WAHIDA",
    business_category: "DCCC",
    lat: 2.1653,
    lng: 117.4886,
    kota: "Kabupaten Berau",
    provinsi: "Kalimantan Timur",
  },
  {
    id: 168,
    nama: "AKHMAD SUBEKTI",
    business_category: "DCSA",
    lat: -7.3612,
    lng: 109.9035,
    kota: "Kabupaten Banjarnegara",
    provinsi: "Jawa Tengah",
  },
  {
    id: 169,
    nama: "RATNA MUSTIKA DEWI",
    business_category: "PCCR",
    lat: -6.9236,
    lng: 107.7163,
    kota: "Kabupaten Bandung",
    provinsi: "Jawa Barat",
  },
  {
    id: 170,
    nama: "VERA NUR RIDWAN",
    business_category: "DCSA",
    lat: -6.8414,
    lng: 108.7069,
    kota: "Kabupaten Cirebon",
    provinsi: "Jawa Barat",
  },

  {
    id: 171,
    nama: "ETIK INDRAWATI",
    business_category: "PCCR",
    lat: -7.4441,
    lng: 112.7172,
    kota: "Kabupaten Sidoarjo",
    provinsi: "Jawa Timur",
  },
  {
    id: 172,
    nama: "SITI NURAENI",
    business_category: "DCSA",
    lat: -6.4517,
    lng: 107.0634,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 173,
    nama: "WINNY VICTORIA",
    business_category: "DCCC",
    lat: -6.1812,
    lng: 106.6896,
    kota: "Kota Tangerang",
    provinsi: "Banten",
  },
  {
    id: 174,
    nama: "JAHROH",
    business_category: "DCCC",
    lat: -6.3698,
    lng: 106.2534,
    kota: "Kabupaten Lebak",
    provinsi: "Banten",
  },
  {
    id: 175,
    nama: "AJI WAHYU SAPUTRO",
    business_category: "DCCC",
    lat: -6.2438,
    lng: 107.0889,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 176,
    nama: "YULIASTRI MUTMAINAH",
    business_category: "DCCC",
    lat: -2.8754,
    lng: 104.2439,
    kota: "Kabupaten Ogan Ilir",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 177,
    nama: "RYAN FEBRIANSYAH",
    business_category: "DCCC",
    lat: -6.3926,
    lng: 106.8347,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 178,
    nama: "UMMI",
    business_category: "DCSA",
    lat: -6.5518,
    lng: 107.6984,
    kota: "Kabupaten Subang",
    provinsi: "Jawa Barat",
  },
  {
    id: 179,
    nama: "BAGAS TRI IRAWAN",
    business_category: "DCCC",
    lat: -7.4209,
    lng: 110.9381,
    kota: "Kabupaten Klaten",
    provinsi: "Jawa Tengah",
  },
  {
    id: 180,
    nama: "ARIN",
    business_category: "DCSA",
    lat: -6.9146,
    lng: 107.6831,
    kota: "Kota Bandung",
    provinsi: "Jawa Barat",
  },

  {
    id: 181,
    nama: "KIKY PUTERI",
    business_category: "DCCC",
    lat: -3.2903,
    lng: 114.5841,
    kota: "Kota Banjarmasin",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 182,
    nama: "MOHD. REZA KURNIAWAN",
    business_category: "DCSA",
    lat: 1.0153,
    lng: 102.7128,
    kota: "Kabupaten Pelalawan",
    provinsi: "Riau",
  },
  {
    id: 183,
    nama: "ULFA TAQWANI",
    business_category: "PFFR",
    lat: 4.6863,
    lng: 96.8554,
    kota: "Kabupaten Aceh Tengah",
    provinsi: "Aceh",
  },
  {
    id: 184,
    nama: "OCTAVIANI YUSTIKA RAHAYU",
    business_category: "DCCC",
    lat: -6.1514,
    lng: 106.9569,
    kota: "Kota Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 185,
    nama: "NOFRI YENI",
    business_category: "DCCC",
    lat: -6.1539,
    lng: 106.7267,
    kota: "Kota Jakarta Barat",
    provinsi: "DKI Jakarta",
  },
  {
    id: 186,
    nama: "INDAH ADNYANI",
    business_category: "DCCC",
    lat: -8.6124,
    lng: 115.1769,
    kota: "Kabupaten Badung",
    provinsi: "Bali",
  },
  {
    id: 187,
    nama: "IRMA",
    business_category: "DCCC",
    lat: 4.1796,
    lng: 117.6823,
    kota: "Kabupaten Nunukan",
    provinsi: "Kalimantan Utara",
  },
  {
    id: 188,
    nama: "SUNIA HERLINA",
    business_category: "DCCC",
    lat: -0.0338,
    lng: 109.3587,
    kota: "Kota Pontianak",
    provinsi: "Kalimantan Barat",
  },
  {
    id: 189,
    nama: "DANTI PUJIANTI",
    business_category: "DCSA",
    lat: -6.8794,
    lng: 109.1326,
    kota: "Kabupaten Brebes",
    provinsi: "Jawa Tengah",
  },
  {
    id: 190,
    nama: "ULPA WULAN SARI",
    business_category: "DCCC",
    lat: -7.0019,
    lng: 106.8226,
    kota: "Kabupaten Sukabumi",
    provinsi: "Jawa Barat",
  },

  {
    id: 191,
    nama: "RADITA PRABASIWI",
    business_category: "DCCC",
    lat: -7.3187,
    lng: 110.5082,
    kota: "Kabupaten Semarang",
    provinsi: "Jawa Tengah",
  },
  {
    id: 192,
    nama: "NI LUH SUPARTINI",
    business_category: "DCCC",
    lat: -8.6696,
    lng: 115.1968,
    kota: "Kota Denpasar",
    provinsi: "Bali",
  },
  {
    id: 193,
    nama: "SYIFA AULIA AZZAHRA",
    business_category: "DPKB",
    lat: -6.3367,
    lng: 106.8994,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 194,
    nama: "LIANI",
    business_category: "CCRO",
    lat: -3.3186,
    lng: 114.5904,
    kota: "Kota Banjarmasin",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 195,
    nama: "NUR CHOLIS",
    business_category: "DPKB",
    lat: -7.4926,
    lng: 110.6263,
    kota: "Kabupaten Sleman",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 196,
    nama: "DWI NASTITI",
    business_category: "DCCC",
    lat: -5.4826,
    lng: 105.3751,
    kota: "Kabupaten Lampung Selatan",
    provinsi: "Lampung",
  },
  {
    id: 197,
    nama: "IVAN",
    business_category: "PFFR",
    lat: 4.6342,
    lng: 96.8439,
    kota: "Kabupaten Aceh Tengah",
    provinsi: "Aceh",
  },
  {
    id: 198,
    nama: "JEFRI FAHMI",
    business_category: "DPKB",
    lat: 0.7362,
    lng: 101.6321,
    kota: "Kabupaten Siak",
    provinsi: "Riau",
  },
  {
    id: 199,
    nama: "CINDY TIANA",
    business_category: "DCCC",
    lat: -1.1765,
    lng: 116.8839,
    kota: "Kabupaten Penajam Paser Utara",
    provinsi: "Kalimantan Timur",
  },
  {
    id: 200,
    nama: "BAHRUL ULUM",
    business_category: "DCSA",
    lat: -6.4087,
    lng: 106.7654,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 201,
    nama: "FITRYANA RISKA RAHMADANI",
    business_category: "DPKB",
    lat: -4.4336,
    lng: 102.8971,
    kota: "Kabupaten Seluma",
    provinsi: "Bengkulu",
  },
  {
    id: 202,
    nama: "DADAN DANURI",
    business_category: "DCSA",
    lat: -6.5586,
    lng: 107.7601,
    kota: "Kabupaten Subang",
    provinsi: "Jawa Barat",
  },
  {
    id: 203,
    nama: "WINDIYAFRANSISKA/UMI",
    business_category: "DCCC",
    lat: -7.684,
    lng: 108.6527,
    kota: "Kabupaten Ciamis",
    provinsi: "Jawa Barat",
  },
  {
    id: 204,
    nama: "IDOLA MARTA EMILIA",
    business_category: "DCCC",
    lat: -1.4583,
    lng: 100.5775,
    kota: "Kabupaten Pesisir Selatan",
    provinsi: "Sumatera Barat",
  },
  {
    id: 205,
    nama: "FATMA KUSUMA LIANI",
    business_category: "DCSA",
    lat: -7.4646,
    lng: 108.9483,
    kota: "Kabupaten Tasikmalaya",
    provinsi: "Jawa Barat",
  },
  {
    id: 206,
    nama: "MUHAMMAD ALFIN PUTRA",
    business_category: "PCCR",
    lat: -3.9973,
    lng: 122.5129,
    kota: "Kota Kendari",
    provinsi: "Sulawesi Tenggara",
  },
  {
    id: 207,
    nama: "AZHARI",
    business_category: "PCCR",
    lat: 0.843,
    lng: 100.3893,
    kota: "Kabupaten Agam",
    provinsi: "Sumatera Barat",
  },
  {
    id: 208,
    nama: "HASNA ABIDATI A",
    business_category: "DCSA",
    lat: -7.565,
    lng: 110.21,
    kota: "Kabupaten Sleman",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 209,
    nama: "LINAH WATI",
    business_category: "CCRO",
    lat: -6.1478,
    lng: 106.7073,
    kota: "Kota Jakarta Barat",
    provinsi: "DKI Jakarta",
  },
  {
    id: 210,
    nama: "MUHAMMAD NOOR IQBAL BAIHAKI",
    business_category: "DCCC",
    lat: -3.2833,
    lng: 114.5908,
    kota: "Kota Banjarmasin",
    provinsi: "Kalimantan Selatan",
  },

  {
    id: 211,
    nama: "MIDAR SANTI",
    business_category: "DCCC",
    lat: 0.5071,
    lng: 101.4478,
    kota: "Kota Pekanbaru",
    provinsi: "Riau",
  },
  {
    id: 212,
    nama: "JANISA",
    business_category: "DCCC",
    lat: -6.3956,
    lng: 106.7363,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 213,
    nama: "NASROH",
    business_category: "DCSA",
    lat: -6.1422,
    lng: 106.2776,
    kota: "Kabupaten Tangerang",
    provinsi: "Banten",
  },
  {
    id: 214,
    nama: "ANIFA",
    business_category: "DCCC",
    lat: -7.1575,
    lng: 112.1835,
    kota: "Kabupaten Lamongan",
    provinsi: "Jawa Timur",
  },
  {
    id: 215,
    nama: "CECEP SUNARYA",
    business_category: "PFFR",
    lat: -6.8344,
    lng: 107.4656,
    kota: "Kabupaten Bandung Barat",
    provinsi: "Jawa Barat",
  },
  {
    id: 216,
    nama: "INTAN FEBRINA",
    business_category: "DCCC",
    lat: 0.3516,
    lng: 101.1787,
    kota: "Kabupaten Kampar",
    provinsi: "Riau",
  },
  {
    id: 217,
    nama: "SHOFI ALMAS HADIA PHASA",
    business_category: "PFFR",
    lat: -7.0526,
    lng: 110.4237,
    kota: "Kota Semarang",
    provinsi: "Jawa Tengah",
  },
  {
    id: 218,
    nama: "ELNIWANTI",
    business_category: "DCCC",
    lat: -0.4526,
    lng: 101.0634,
    kota: "Kabupaten Kampar",
    provinsi: "Riau",
  },
  {
    id: 219,
    nama: "DIAZ PUTRI",
    business_category: "CCRO",
    lat: -3.8457,
    lng: 102.3396,
    kota: "Kota Bengkulu",
    provinsi: "Bengkulu",
  },
  {
    id: 220,
    nama: "RIKI WIRA YUDA NUR",
    business_category: "PFFR",
    lat: -6.3054,
    lng: 107.2965,
    kota: "Kabupaten Karawang",
    provinsi: "Jawa Barat",
  },

  {
    id: 221,
    nama: "DITA FARIKHIANTI",
    business_category: "DCCC",
    lat: -7.5856,
    lng: 110.2625,
    kota: "Kabupaten Sleman",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 222,
    nama: "DJUMADI",
    business_category: "DCCC",
    lat: -6.4026,
    lng: 106.9104,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 223,
    nama: "ANIN DIYAJATI",
    business_category: "PFFR",
    lat: -7.6281,
    lng: 111.5214,
    kota: "Kabupaten Madiun",
    provinsi: "Jawa Timur",
  },
  {
    id: 224,
    nama: "RITA HELINGO",
    business_category: "DCSA",
    lat: 0.6506,
    lng: 122.6412,
    kota: "Kabupaten Bone Bolango",
    provinsi: "Gorontalo",
  },
  {
    id: 225,
    nama: "ANITA",
    business_category: "DPKB",
    lat: -6.2167,
    lng: 106.5078,
    kota: "Kota Tangerang",
    provinsi: "Banten",
  },
  {
    id: 226,
    nama: "ADELIA IRMANSYAH",
    business_category: "DCSA",
    lat: -6.7205,
    lng: 106.7934,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 227,
    nama: "ADNAN",
    business_category: "PFFR",
    lat: 4.1443,
    lng: 96.1266,
    kota: "Kabupaten Aceh Barat",
    provinsi: "Aceh",
  },
  {
    id: 228,
    nama: "SALMA CAHYANINGRUM",
    business_category: "CCRO",
    lat: -6.2446,
    lng: 107.1342,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 229,
    nama: "YANI",
    business_category: "DCCC",
    lat: -6.3036,
    lng: 106.7915,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 230,
    nama: "MAHAPRAMITHA DHARMA PUTRI",
    business_category: "CCRO",
    lat: -6.256,
    lng: 106.6766,
    kota: "Kota Tangerang Selatan",
    provinsi: "Banten",
  },

  {
    id: 231,
    nama: "JEFRI",
    business_category: "PFFR",
    lat: -2.9909,
    lng: 104.7566,
    kota: "Kota Palembang",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 232,
    nama: "NOLITA NIVELLA",
    business_category: "DCCC",
    lat: 1.5493,
    lng: 124.913,
    kota: "Kota Manado",
    provinsi: "Sulawesi Utara",
  },
  {
    id: 233,
    nama: "FIRO",
    business_category: "DCSA",
    lat: -7.1536,
    lng: 112.6575,
    kota: "Kabupaten Sidoarjo",
    provinsi: "Jawa Timur",
  },
  {
    id: 234,
    nama: "DINI",
    business_category: "PCCR",
    lat: -2.9727,
    lng: 104.7458,
    kota: "Kota Palembang",
    provinsi: "Sumatera Selatan",
  },
  {
    id: 235,
    nama: "MAWADDAH KATANIA PUTRI",
    business_category: "DCCC",
    lat: -3.7928,
    lng: 102.2608,
    kota: "Kabupaten Bengkulu Tengah",
    provinsi: "Bengkulu",
  },
  {
    id: 236,
    nama: "RESI TRIA ULY ANA",
    business_category: "DCCC",
    lat: -6.3008,
    lng: 107.1416,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 237,
    nama: "SUKMA WIBOWO",
    business_category: "DCCC",
    lat: -7.3722,
    lng: 108.5413,
    kota: "Kabupaten Tasikmalaya",
    provinsi: "Jawa Barat",
  },
  {
    id: 238,
    nama: "SIFA'UL QOLBIYAH",
    business_category: "DCCC",
    lat: -6.2527,
    lng: 107.0747,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 239,
    nama: "DEDI",
    business_category: "DCSA",
    lat: -6.9383,
    lng: 107.5786,
    kota: "Kota Bandung",
    provinsi: "Jawa Barat",
  },
  {
    id: 240,
    nama: "YUNA",
    business_category: "PFFR",
    lat: -0.4314,
    lng: 103.2556,
    kota: "Kabupaten Indragiri Hulu",
    provinsi: "Riau",
  },

  {
    id: 241,
    nama: "SYALOM YOSUA IMANUEL PANGLORO",
    business_category: "DCCC",
    lat: 3.3274,
    lng: 117.5785,
    kota: "Kabupaten Nunukan",
    provinsi: "Kalimantan Utara",
  },
  {
    id: 242,
    nama: "CUCU NURBUDIATI",
    business_category: "DCCC",
    lat: -6.8321,
    lng: 107.8937,
    kota: "Kabupaten Sumedang",
    provinsi: "Jawa Barat",
  },
  {
    id: 243,
    nama: "RISZA",
    business_category: "CCRO",
    lat: -6.3256,
    lng: 106.9018,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 244,
    nama: "SURANTO",
    business_category: "DCCC",
    lat: -7.5484,
    lng: 110.8361,
    kota: "Kabupaten Klaten",
    provinsi: "Jawa Tengah",
  },
  {
    id: 245,
    nama: "RAHMAWATI",
    business_category: "CCRO",
    lat: -3.6935,
    lng: 114.7056,
    kota: "Kabupaten Banjar",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 246,
    nama: "SUNTARA AHMAD DIMYATI",
    business_category: "DCCC",
    lat: -6.3484,
    lng: 107.0304,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 247,
    nama: "AHMAD MUHAJIR",
    business_category: "DCCC",
    lat: -3.4447,
    lng: 114.8293,
    kota: "Kabupaten Barito Kuala",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 248,
    nama: "NINUK SUGIARTI",
    business_category: "DCSA",
    lat: -5.3616,
    lng: 105.0294,
    kota: "Kabupaten Lampung Selatan",
    provinsi: "Lampung",
  },
  {
    id: 249,
    nama: "WAHID SUPRIYANTO",
    business_category: "DCCC",
    lat: -7.7972,
    lng: 110.3671,
    kota: "Kota Yogyakarta",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 250,
    nama: "HESTI YULIANTI",
    business_category: "PFFR",
    lat: 0.4914,
    lng: 101.4472,
    kota: "Kota Pekanbaru",
    provinsi: "Riau",
  },

  {
    id: 251,
    nama: "RAGHAD NOR ARIFAH",
    business_category: "DCSA",
    lat: -7.1504,
    lng: 113.5201,
    kota: "Kabupaten Pamekasan",
    provinsi: "Jawa Timur",
  },
  {
    id: 252,
    nama: "MUHAMMAD RIFAI",
    business_category: "DCCC",
    lat: -6.2942,
    lng: 107.1719,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 253,
    nama: "YATI ADE",
    business_category: "DCCC",
    lat: -6.3259,
    lng: 106.6454,
    kota: "Kota Tangerang Selatan",
    provinsi: "Banten",
  },
  {
    id: 254,
    nama: "AANG JUNAIDY",
    business_category: "DCCC",
    lat: -6.1166,
    lng: 106.881,
    kota: "Kota Jakarta Utara",
    provinsi: "DKI Jakarta",
  },
  {
    id: 255,
    nama: "MISRAN S",
    business_category: "DPKB",
    lat: 3.5553,
    lng: 98.7135,
    kota: "Kota Medan",
    provinsi: "Sumatera Utara",
  },
  {
    id: 256,
    nama: "NUR PITRIANI",
    business_category: "DCCC",
    lat: -6.8176,
    lng: 107.3114,
    kota: "Kabupaten Bandung Barat",
    provinsi: "Jawa Barat",
  },
  {
    id: 257,
    nama: "GRACELLA",
    business_category: "PFFR",
    lat: 0.5236,
    lng: 101.1082,
    kota: "Kabupaten Kampar",
    provinsi: "Riau",
  },
  {
    id: 258,
    nama: "ADJIE NUGRAHA",
    business_category: "DCCC",
    lat: -6.9377,
    lng: 107.5733,
    kota: "Kota Bandung",
    provinsi: "Jawa Barat",
  },
  {
    id: 259,
    nama: "ELLY RAHMAWATI",
    business_category: "DPKB",
    lat: -6.6766,
    lng: 106.6627,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 260,
    nama: "DEVI ALLIANI",
    business_category: "PCCR",
    lat: -8.0984,
    lng: 112.1682,
    kota: "Kabupaten Malang",
    provinsi: "Jawa Timur",
  },

  {
    id: 261,
    nama: "AHMAD ISWANTO",
    business_category: "DCCC",
    lat: -6.3157,
    lng: 107.1353,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 262,
    nama: "NAILA MAWAHDA BRAHIM",
    business_category: "DCCC",
    lat: -6.2438,
    lng: 106.8443,
    kota: "Kota Jakarta Timur",
    provinsi: "DKI Jakarta",
  },
  {
    id: 263,
    nama: "JIHAN DLIYA",
    business_category: "DCCC",
    lat: -6.1099,
    lng: 106.9325,
    kota: "Kota Jakarta Utara",
    provinsi: "DKI Jakarta",
  },
  {
    id: 264,
    nama: "HANA GERHANA",
    business_category: "DCCC",
    lat: -7.3054,
    lng: 108.3821,
    kota: "Kabupaten Tasikmalaya",
    provinsi: "Jawa Barat",
  },
  {
    id: 265,
    nama: "ELIS RISMAWATI",
    business_category: "DCSA",
    lat: -6.1198,
    lng: 106.5232,
    kota: "Kota Tangerang",
    provinsi: "Banten",
  },
  {
    id: 266,
    nama: "BARY DEWANDA PUTRA",
    business_category: "PFFR",
    lat: 0.5079,
    lng: 101.4635,
    kota: "Kota Pekanbaru",
    provinsi: "Riau",
  },
  {
    id: 267,
    nama: "FIRMAN HADJATU",
    business_category: "DCCC",
    lat: -1.2155,
    lng: 121.4834,
    kota: "Kabupaten Morowali",
    provinsi: "Sulawesi Tengah",
  },
  {
    id: 268,
    nama: "ANA",
    business_category: "DPKB",
    lat: -6.8048,
    lng: 110.8417,
    kota: "Kabupaten Jepara",
    provinsi: "Jawa Tengah",
  },
  {
    id: 269,
    nama: "DEVI",
    business_category: "PCCR",
    lat: -3.384,
    lng: 126.7266,
    kota: "Kabupaten Maluku Tengah",
    provinsi: "Maluku",
  },
  {
    id: 270,
    nama: "JESSYCA JUWITA",
    business_category: "DCCC",
    lat: -6.2353,
    lng: 106.979,
    kota: "Kota Bekasi",
    provinsi: "Jawa Barat",
  },

  {
    id: 271,
    nama: "UTYA FIDDINI SJAMSUDDIN",
    business_category: "DCCC",
    lat: -6.4026,
    lng: 106.9104,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 272,
    nama: "YULIANTY MAGDALENA",
    business_category: "DCCC",
    lat: -6.3186,
    lng: 106.8817,
    kota: "Kota Depok",
    provinsi: "Jawa Barat",
  },
  {
    id: 273,
    nama: "FAWWAZ MAHDY TAUFIQ",
    business_category: "DCCC",
    lat: -6.4011,
    lng: 106.7524,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 274,
    nama: "HUSNUN FADILLAH",
    business_category: "DCSA",
    lat: -1.0947,
    lng: 113.8746,
    kota: "Kabupaten Katingan",
    provinsi: "Kalimantan Tengah",
  },
  {
    id: 275,
    nama: "MARIANI/ANHI",
    business_category: "DCCC",
    lat: -3.5634,
    lng: 119.7731,
    kota: "Kabupaten Polewali Mandar",
    provinsi: "Sulawesi Barat",
  },
  {
    id: 276,
    nama: "ARSILIA LAILITA SARI",
    business_category: "DCCC",
    lat: -7.7702,
    lng: 110.2935,
    kota: "Kabupaten Bantul",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 277,
    nama: "CLARITA",
    business_category: "PFFR",
    lat: -7.2764,
    lng: 112.7939,
    kota: "Kota Surabaya",
    provinsi: "Jawa Timur",
  },
  {
    id: 278,
    nama: "MARIA ULFA",
    business_category: "DCSA",
    lat: -7.7395,
    lng: 113.1852,
    kota: "Kabupaten Probolinggo",
    provinsi: "Jawa Timur",
  },
  {
    id: 279,
    nama: "POPONG RUKIAH",
    business_category: "DCSA",
    lat: -7.2119,
    lng: 108.3771,
    kota: "Kabupaten Tasikmalaya",
    provinsi: "Jawa Barat",
  },
  {
    id: 280,
    nama: "DIANOVITA JUSTITIA",
    business_category: "DCCC",
    lat: -6.7476,
    lng: 108.5506,
    kota: "Kabupaten Majalengka",
    provinsi: "Jawa Barat",
  },

  {
    id: 281,
    nama: "NUR AZIZAH",
    business_category: "DCSA",
    lat: -8.0776,
    lng: 111.7154,
    kota: "Kabupaten Trenggalek",
    provinsi: "Jawa Timur",
  },
  {
    id: 282,
    nama: "SAMSIR JAYA",
    business_category: "PFFR",
    lat: -8.4963,
    lng: 140.3947,
    kota: "Kabupaten Merauke",
    provinsi: "Papua Selatan",
  },
  {
    id: 283,
    nama: "HERDA",
    business_category: "PFFR",
    lat: -6.8897,
    lng: 109.6745,
    kota: "Kabupaten Pemalang",
    provinsi: "Jawa Tengah",
  },
  {
    id: 284,
    nama: "BU ABI",
    business_category: "DCCC",
    lat: -8.636,
    lng: 115.2303,
    kota: "Kota Denpasar",
    provinsi: "Bali",
  },
  {
    id: 285,
    nama: "TUTI HAWIYAH",
    business_category: "DCSA",
    lat: -2.6504,
    lng: 101.1281,
    kota: "Kabupaten Kerinci",
    provinsi: "Jambi",
  },
  {
    id: 286,
    nama: "ROJALI",
    business_category: "DCCC",
    lat: -6.1074,
    lng: 107.5146,
    kota: "Kabupaten Karawang",
    provinsi: "Jawa Barat",
  },
  {
    id: 287,
    nama: "ANITA (BUTIK HUMAIRA)",
    business_category: "DPKB",
    lat: -2.5847,
    lng: 115.3831,
    kota: "Kabupaten Kotabaru",
    provinsi: "Kalimantan Selatan",
  },
  {
    id: 288,
    nama: "RINA WIDYANINGRUM",
    business_category: "DPKB",
    lat: -7.2251,
    lng: 110.3514,
    kota: "Kabupaten Semarang",
    provinsi: "Jawa Tengah",
  },
  {
    id: 289,
    nama: "FIRMAN FAJAR",
    business_category: "DCSA",
    lat: -4.0223,
    lng: 120.1995,
    kota: "Kabupaten Bone",
    provinsi: "Sulawesi Selatan",
  },
  {
    id: 290,
    nama: "NURMADINA",
    business_category: "PFFR",
    lat: -3.4489,
    lng: 119.3452,
    kota: "Kabupaten Majene",
    provinsi: "Sulawesi Barat",
  },

  {
    id: 291,
    nama: "MONICA INDAH WIDARTI",
    business_category: "DCSA",
    lat: -7.8754,
    lng: 110.3311,
    kota: "Kabupaten Bantul",
    provinsi: "DI Yogyakarta",
  },
  {
    id: 292,
    nama: "UNAY/DEDE",
    business_category: "PFFR",
    lat: -6.1786,
    lng: 106.6367,
    kota: "Kota Tangerang",
    provinsi: "Banten",
  },
  {
    id: 293,
    nama: "SIDHA/GRIA",
    business_category: "CCRO",
    lat: -7.8861,
    lng: 112.6646,
    kota: "Kota Malang",
    provinsi: "Jawa Timur",
  },
  {
    id: 294,
    nama: "SUCI",
    business_category: "DCSA",
    lat: -7.0193,
    lng: 107.7457,
    kota: "Kabupaten Bandung",
    provinsi: "Jawa Barat",
  },
  {
    id: 295,
    nama: "SUTOMO",
    business_category: "DCCC",
    lat: -6.1921,
    lng: 106.8926,
    kota: "Kota Jakarta Timur",
    provinsi: "DKI Jakarta",
  },
  {
    id: 296,
    nama: "SALAWI",
    business_category: "DCCC",
    lat: -7.0812,
    lng: 113.4749,
    kota: "Kabupaten Pamekasan",
    provinsi: "Jawa Timur",
  },
  {
    id: 297,
    nama: "R.SARTIKA DEWI",
    business_category: "DPKB",
    lat: -0.4786,
    lng: 103.1795,
    kota: "Kabupaten Indragiri Hulu",
    provinsi: "Riau",
  },
  {
    id: 298,
    nama: "ASNAINI",
    business_category: "DCCC",
    lat: -6.1413,
    lng: 107.0196,
    kota: "Kabupaten Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    id: 299,
    nama: "NELVIA",
    business_category: "DCCC",
    lat: -6.5711,
    lng: 106.7931,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
  {
    id: 300,
    nama: "AGUNG ZULHAIDIR",
    business_category: "DCCC",
    lat: -6.5728,
    lng: 106.7348,
    kota: "Kabupaten Bogor",
    provinsi: "Jawa Barat",
  },
];

export default mitra;
